# Generated by Django 6.0.3 on 2026-03-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], default='5', max_length=100)),
                ('text', models.CharField(default='good car', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.numbercar')),
            ],
        ),
    ]
