# Generated by Django 6.0.3 on 2026-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите язык програмирование')),
                ('description', models.TextField(verbose_name='описание языка програмирование')),
                ('image', models.ImageField(upload_to='proglang/', verbose_name='загрузите фото')),
                ('created_date_lang', models.PositiveBigIntegerField(blank=True, verbose_name='год создание яп')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'язык програмирование',
                'verbose_name_plural': 'языки програмирование',
            },
        ),
    ]
