# Generated by Django 6.0.3 on 2026-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='viki_url',
            field=models.URLField(null=True, verbose_name='вставьте ссылку с википедии'),
        ),
    ]
