# Generated by Django 6.0.3 on 2026-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0002_proglang_viki_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='file_python',
            field=models.FileField(null=True, upload_to='files/', verbose_name='загрузите файл'),
        ),
    ]
